stages:
  - prepare
  - build
  - upload

variables:
  CONTAINER_NAME: "$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"

  # Define the rootfs path with unique identifiers for each namespace/project
  ROOTFS_PATH: "/mnt/gitlab-rootfs/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"

  ROOTFS_REPO_FOLDER: "rootfs.src"

pos:
  stage: build
  script:
    - echo "Creating persistent directory on the runner host at $ROOTFS_PATH"
    - mkdir -p $ROOTFS_PATH
    - docker build . -t $CONTAINER_NAME
    - docker run --privileged -v $ROOTFS_PATH:/root/pos/$ROOTFS_REPO_FOLDER -t --env PATH="/opt/toolchains/gcc-linaro-11.3.1-2022.06-x86_64_arm-linux-gnueabihf/bin:$PATH" $CONTAINER_NAME sh -c "git checkout $ROOTFS_REPO_FOLDER && ./build_rootfs.sh"
  tags:
    - runners-server,shell

upload_artifact:
  stage: upload
  script:
    - echo "Uploading rootfs.cpio artifact"
    - cp $ROOTFS_PATH/board/virt32/rootfs.cpio virt32.rootfs.cpio
    - cp $ROOTFS_PATH/board/virt64/rootfs.cpio virt64.rootfs.cpio
    # - cp $ROOTFS_PATH/board/rpi4/rootfs.cpio rpi4.rootfs.cpio
    # - cp $ROOTFS_PATH/board/rpi4_64/rootfs.cpio rpi4_64.rootfs.cpio
  artifacts:
    paths:
      - virt32.rootfs.cpio
      - virt64.rootfs.cpio
      # - rpi4.rootfs.cpio
      # - rpi4_64.rootfs.cpio
    expire_in: never
  tags:
    - runners-server,shell

clean:
  stage: prepare
  script:
    - rm $ROOTFS_PATH
  when: manual
  tags:
    - runners-server,shell
  
