stages:
  - prepare
  - build
  - upload

variables:
  CONTAINER_NAME: "pos_container"

  # Define the rootfs path with unique identifiers for each namespace/project
  ROOTFS_PATH: "/mnt/gitlab-rootfs/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"

pos:
  stage: build
  script:
    - echo "Creating persistent directory on the runner host at $ROOTFS_PATH"
    - mkdir -p $ROOTFS_PATH
    - docker build . -t $CONTAINER_NAME
    - docker run --privileged -t --env PATH="/opt/toolchains/gcc-linaro-11.3.1-2022.06-x86_64_arm-linux-gnueabihf/bin:$PATH" --mount source=rootfs,target=/root/pos24/rootfs $CONTAINER_NAME sh -c ./build_rootfs.sh
    - echo "Copying file from the Docker image..."
    - docker run --rm -v "$(pwd):/mnt/host" -t --mount source=rootfs,target=/root/pos24/rootfs $CONTAINER_NAME sh -c "cp /root/pos24/rootfs/board/virt32/rootfs.cpio /mnt/host/"
    - cp rootfs.cpio $ROOTFS_PATH
  tags:
    - runners-server,shell

upload_artifact:
  stage: upload
  script:
    - echo "Uploading rootfs.cpio artifact"
    - cp $ROOTFS_PATH/rootfs.cpio .
  artifacts:
    paths:
      - rootfs.cpio
    expire_in: never
  tags:
    - runners-server,shell

clean:
  stage: prepare
  script:
    - docker run --rm -v "$(pwd):/mnt/host" -t --mount source=rootfs,target=/root/pos24-main/rootfs $CONTAINER_NAME sh -c "rm -rf /root/pos24-main/rootfs/*"
  when: manual
  tags:
    - runners-server,shell
  
