#!/bin/bash

export PYTHONPATH=sense-hat/out/lib/python2.7/site-packages/

function qemu {
 echo Running QEMU
 ./st
  pkill -9 -f sense-hat-server.py 2>/dev/null
}

# Prevent old sense-hat instances to be running
pkill -9 -f sense-hat-server.py 2>/dev/null

# sense-hat-server will send a SIGUSR1 signal when the tcp server is started
# so wait for this signal before starting qemu
trap qemu SIGUSR1

python3 sense-hat/sense-hat-server.py $$ &

wait
